### ISSUE TITLE
Automate integration tests using GitHub Actions

### ISSUE THREAD

**Issue by aneudecker** [INWTlab/r-kafka-client#3]
Test from `tests` folder should run automatically with every commit using GitHub actions

Ideas:
- Create cluster in docker container using trivup
- Run tests against cluster using `devtools::test()`
- Make kafka broker version configurable
- Run on different operating systems

**Comment by wahani** [comment]
- Action was configured using: https://github.com/r-lib/actions/tree/v2-branch/examples#standard-ci-workflow
- Updates on installation instructions are added to Readme
- Updates on using docker-compose are added to Readme. Setup was created following https://hackernoon.com/setting-up-kafka-on-docker-for-local-development
- docker-compose setup in GitHub action was created following
    - https://stackoverflow.com/questions/65914287/github-action-with-mysql-test-database
    - https://github.com/actions/runner-images/issues/17

**Comment by wahani** [comment]
- Action for ubuntu-latest was added
- Configured portable names in docker-compose.yml to be able to execute docker exec in pipeline step
- Set environment variables to configure topic and brokers to be used in several steps

**Comment by wahani** [comment]
- On MacOS we have the problem, that environment variables are not picked up in the same way. We have to use .Renviron files to configure BROKERS and TOPIC. This works now.
- We still have an error in the integration tests on MacOS which is reported in #2 

I will ══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-commit.R:21:3'): Committing throws no error ────────────────────
<Rcpp::exception/C++Error/error/condition>
Error: Error: Failed commit: Local: No offset stored
Backtrace:
    ▆
 1. └─consumer$commit(async = FALSE) at test-commit.R:21:3

[ FAIL 1 | WARN 0 | SKIP 0 | PASS 8 ]
Error: Error: Test failures
Execution halted
